apiVersion: v1
kind: Service
metadata:
  name: custom-service
spec:
  type: NodePort
  selector:
    app: custom-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080  # You can change this to any available port
